### ISSUE TITLE
support drill-down to genotypes

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#11]
For IMPC and potentially zfin use, we'd like to be able to drill-down from a gene to individual genotypes/strains affecting this gene. 

This might mean, for example, clicking on a model name in a column and expanding out that column into multiple sub-columns, one for each related genotype.

Chuck has some thoughts on how this might be implemented in a focus+context model. Other options can be discussed.

**Comment by yuanzhou** [comment]
According to @harryhoch 's suggestion, I'll work on this genotype expansion by starting with the data loading test, if the performance issue can be resolved, I'll continue to work on the UI design.

**Comment by yuanzhou** [comment]
@harryhoch Made some good progress this week on geno type expansion. Now we could grab the genotype data and throw them into the dataLoader, then transform the format. Update the axis render for target list. Then reorder the target list to place genotypes right after the parent gene. I also add some basic styling to the added genotypes. And every time there's new genotypes added, the grid and mini map still stay at the current view, but push the rest of the data down.

1. Will need to clean up the code to have a leaner process since source list won't need to be updated. 

2. Add animations to the genotypes show up.

3. Try to figure out how to hide the genotypes when collapse. Maybe add cache.

4. Some unmatched phenotypes may also find new matches once the genotypes added.

**Comment by harryhoch** [comment]
@yuanzhou, thanks. this sounds like good progress. #4 is a good question that we will have to address - let's discuss when you're ready.

**Comment by yuanzhou** [comment]
@harryhoch when you have a chance, can we talk about this genotype expansion? Right now I have the basic insert/remove work, but there are couple of weird renderings, prob due to the returned JSON data. One issue I've added on monarch-app's issue page: https://github.com/monarch-initiative/monarch-app/issues/1024. I'm not confident to merge this feature to the master branch at this point.

**Comment by harryhoch** [comment]
agreed. We can certainly talk, but we need help from others to fix the data....

**Comment by yuanzhou** [comment]
Thanks! Do you have any suggestions on the UI or inserting/removing animations? 

![capture](https://cloud.githubusercontent.com/assets/195873/10611282/6c57f524-7719-11e5-8bd1-3378a9e0110b.PNG)

![capture2](https://cloud.githubusercontent.com/assets/195873/10611283/6e7599ba-7719-11e5-9596-5b207e62d20a.PNG)

I'm also thinking about using a overlay to block the widget when it goes out to fetch the genotypes and calculates the matches with the compare API. Sometimes it's very fast to see the rendering, sometimes it may take several seconds or longer.

**Comment by yuanzhou** [comment]
@harryhoch I'm just wondering why you display genes for mouse and fish, but diseases for human? I'll need to use a flag to mark if there's already expanded genotypes for each species. And I was thinking if I can just loop through the targetGGroups from https://github.com/monarch-initiative/phenogrid/blob/master/config/phenogrid_config.js#L6 . Maybe I should create something silimar to this:

````
expandedGenotyps: [ 
                {name: "Homo sapiens", hasExpandedGenotyps: false},
                 {name: "Mus musculus", hasExpandedGenotyps: false},
                 {name: "Danio rerio", hasExpandedGenotyps: false}
            ]
````

May need to `Drosophila melanogaster` or `UDPICS` (not sure). So can I remove Homo sapiens from the list? This led me to think why human uses diseases for targets.

**Comment by harryhoch** [comment]
@yuanzhou, I think we talk about human diseases because they are so often described in such detail by resources such as OMIM, which also contains genotypic information. I think your model for the expansion is fine. I think you can remove homo sapiens.

**Comment by yuanzhou** [comment]
@harryhoch, I've had the loaded genotype data stored in the widget status and now the  insertion checks if the target gene's genotypes have been loaded, just update the status and render them, no ajax call involved. Removal also hides the added genotypes in underlying data. Switching between single species or multi-species keeps the status of expanded genotypes for each species.

I thought about adding animations or simply some color backgrounds to the added genotype corresponding grid cells in the grid. Haven't come up any good workarounds. Because the grid is created row by row, columns only contain the column labels. It's feasible when we are in the inverted axis mode, since in this mode the expanded genotypes are created on the rows. When they are showing as column labels, createrow can't render the genotype columns.

So far the https://github.com/monarch-initiative/phenogrid/tree/genotype-expansion branch is a working version of the genotype expansion feature. There are possible bugs due to the data issues if some returned data doesn't have the desired properties. Kent mentioned that his should be resolved in the next data release. Maybe by that time we can merge this feature to the master branch.

**Comment by harryhoch** [comment]
@yuanzhou, Thanks. This looks pretty good. We might have to look into additional feedback to indicate that the expansion is in progress, and to emphasize the difference between gene and genotype rows/columns, but this is a great start.

Regarding animation, let's talk.  The Les Miserables example does the animation by changing the xdomain, setting a transition, and then changing the transforms. we might be able to do something similar.

**Comment by yuanzhou** [comment]
Thanks @harryhoch, I'm using a spinner icon inside the tooltip to indicate the expanding, may not be the best way, but better than nothing and it's very simple.

I'll take a look at the Les Miserables example.

**Comment by harryhoch** [comment]
@yuanzhou, sounds good.

**Comment by yuanzhou** [comment]
@harryhoch I checked the code of Les Miserables D3, the phenogrid cell grid is created based on the Les Miserables. The transition applied to Les Miserables reorder essentially applied to all the rows (row label + cells) and columns (only column label). In our genotype type expansion, if we use transition animation, it will be applied to all the rows and columns. We still couldn't only animate the added genotype lables and their matching grid cells. 

I did add a border to all the newly added cells so they look different from the existing cells. I'm not satisfied with this since the red border doesn't look very nice. I'll continue thinking about this. Please also let me know if you have any other feasible ideas.

![capture](https://cloud.githubusercontent.com/assets/195873/10702487/0c49e5ee-7998-11e5-9073-5c23f0b17d5f.PNG)

**Comment by harryhoch** [comment]
@yuanzhou, ok. I guess I was just thinking that we could try to do a similar change to the data structure and apply the resulting transition. Have you tried it?

regarding the cells, how about a change in background to those columns...

**Comment by nlwashington** [comment]
@harryhoch 's suggestion is reasonable for changing the background of those columns.  alternatively, you could put a border around the block of columns that got added, but the background change might look nicer (very light grey, perhaps).

**Comment by yuanzhou** [comment]
Due to how phenogrid creates those grid cells, it's very tricky to add the backgrounds for those expanded genotypes. Basically we added the data first then rerender all the grid cells at once. But I finally figured out a way to add those backgrounds for each genotype column/row.

![capture](https://cloud.githubusercontent.com/assets/195873/10733911/291f611c-7bd7-11e5-9f94-65ed278760b4.PNG)

![capture](https://cloud.githubusercontent.com/assets/195873/10733974/6729dc6c-7bd7-11e5-88ed-0e1671c12b8c.PNG)

I think it's easier to identify the expanded columns/rows (after inverting).

@harryhoch @nlwashington like it?

**Comment by yuanzhou** [comment]
@harryhoch I'm also thinking about maybe I can add some animation to the grey background by giving it a delay then slide in or some other animations once all the cells are there. I'll think about that later.

**Comment by yuanzhou** [comment]
Just a note of api related issues that need to be addresses in this feature once they are resolved in the monarch api level or there's a decision made:

1. https://github.com/monarch-initiative/monarch-app/issues/1025

2. https://github.com/monarch-initiative/monarch-app/issues/1032

3. https://github.com/monarch-initiative/monarch-app/issues/1024

**Comment by yuanzhou** [comment]
Also noticed a bug that when mouseout the added genotype cells, their tooltip stays there. Will need to fix this.

**Comment by yuanzhou** [comment]
PR #211 merged this genotype expansion feature. But it's disabled for now in the tooltiprender until we have all the api level issues get addressed.

**Comment by harryhoch** [comment]
@yuanzhou, can we close this issue?

**Comment by yuanzhou** [comment]
@harryhoch thanks for reminding me this. All related issues have been addressed I think. I'll close it.
