### ISSUE TITLE
check on unmatched phenotypes.

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#122]
@yuanzhou - please look into the unmatched phenotypes and see if it is working correctly.

**Comment by yuanzhou** [comment]
@harryhoch I tried to see how the output of unmatched phenotypes look like, but there's nothing showed up after I clicked that checkbox, and the Homo sapiens says there's no Unmatched phenotypes. Do I need to add some random phenotypes in the config to see this?

**Comment by harryhoch** [comment]
Yes, that’s probably worth a try.

> On 27 Jul 2015, at 9:00 AM, yuanzhou <notifications@github.com> wrote:
> 
> @harryhoch I tried to see how the output of unmatched phenotypes look like, but there's nothing showed up after I clicked that checkbox, and the Homo sapiens says there's no Unmatched phenotypes. Do I need to add some random phenotypes in the config to see this?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu 		412 648 9300

**Comment by davism84** [comment]
Possible solution for the refactoring unmatched list that Joe and I talked about: 
1. include unmatched phenotypes within the full grid listing, but have the font as strike-through or grayed out. 
2. include in the control options panel an checkbox option to toggle on/off the unmatched items (could also default them to be turned-off and provide an indicator that notes there are unmatched sources

note: if we add these to grid, they will be sorted by frequency of which the will appear at the bottom of the list

**Comment by harryhoch** [comment]
how does #2 differ from what we have now?

**Comment by davism84** [comment]
the toggle is the same, but what we are proposing it to just keep unmatched within the grid verse at the bottom of the screen.

**Comment by harryhoch** [comment]
at the bottom. They could become cumbersome in the grid

**Comment by davism84** [comment]
ok, no problem

**Comment by yuanzhou** [comment]
Unmatched phenotypes is working now. Refactored the unmatched HTML rendering/jquery toggle, and  added ajax to fetch the unmatched phenotype label since it's not presented in the `unmatchedPhenotypes` array.

Notes: 

- For phenotype page, the id format in URL, e.g., HP_0000746 will be redirected to HP:0000746
- For monarch-app json API, phenotype id format must be HP:0000746, don't use HP_0000746, because http://beta.monarchinitiative.org/phenotype/HP_0000746.json will be redirected to http://beta.monarchinitiative.org/phenotype/HP:0000746 (.json extension will be missing after redirection)

**Comment by yuanzhou** [comment]
Further debugging with Mike showed us that the phenotype label is not in the `unmatchedPhenotypes` array. But when embed phenogrid into monarch-app, the disease page returns the `phenotype_list` based that that disease, and the returned array contains label of each phenotype. That's why it worked with monarch-app, but didn't work as a standalone app.
