### ISSUE TITLE
need to add the unmatched phenotypes 

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/phenogrid#158]
unmatched list functionality needs restored in refact-md version

**Comment by yuanzhou** [comment]
Right now in the master and release branch (they have the same code base) the unmatched list only returns the phenotype IDs, sometimes monarch-app's phenotype_list.json doesn't return all the unmatched labels. So we are using chainable ajax aysnc calls for each phenotype to grab the label. This results many HTTP round-trips. Maybe we need to create a new API to accept a bunch of phenotypes in one ajax call and return all the labels.

**Comment by yuanzhou** [comment]
From Harry:

> the real point is that we can do a single monarch-app call or a SciGraph call to get the label for a single phenotype, but we’d like to get multiple labels for phenogrid with only one call from the client.

There are at least two ways to do this: (a) to add a call to SciGraph, or (b) to add a call to monarch-app to do the loop call.  The question really boils down to whether either would be preferred, or if some other option is better…

**Comment by yuanzhou** [comment]
See here for more discussions: https://github.com/monarch-initiative/monarch-app/issues/935

**Comment by yuanzhou** [comment]
Added unmatched sources, buggy, will also play with the display.

**Comment by yuanzhou** [comment]
@harryhoch @davism84 Question:

After some debugging with unmatched phenotypes, I still feel the async ajax calls to grab the labels are not solid, because even if we append those labels to html in the ajax callback, it still may take longer sometimes to show up those labels after users click the unmatched phenotypes button. Unless we show a loading spinner-like image to tell users to wait.

Would it be an alternative if we simply display all the unmatched phenotype IDs? I believe many times not everyone has a clear understanding of what those labels mean. They still need to click the ID link to look up more info. Similar to genes, those gene names/labels are not more meaningful than IDs.

**Comment by harryhoch** [comment]
@yuanzhou 

1. how long are we talking about?  
2. Are we getting the labels back from the original call? I had thought that Kent was adding this functionality back in?
3. Would it be too hard to add a spinner?

I really don't like the idea of the IDs - too low-level and not particularly usable...

**Comment by yuanzhou** [comment]
Thanks @harryhoch Kent only added the labels back to `phenotypes_list.json` for monarch-app, when running phenogrid separately, we still need to go grab the labels. I've put the formatting labels in ajax callbacks, works better than the former version. Now I'll just wait until someone added those labels in the simsearch result.

**Comment by yuanzhou** [comment]
Added and merged Unmatched Phenotypes in PR #172 

![capture](https://cloud.githubusercontent.com/assets/195873/9885600/fed7c72a-5bb3-11e5-9fe2-32bb4146ac65.PNG)

![capture2](https://cloud.githubusercontent.com/assets/195873/9885626/266556ea-5bb4-11e5-84c8-5996833751ea.PNG)

Will make the "Unmatched Sources" wording configurable later. Will also create another new issue for possible bugs related unmatched phenotypes.
