### ISSUE TITLE
remove ./dist file  from git - add to .gitignore

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#168]
might require comparable changes in monarch-app

**Comment by yuanzhou** [comment]
It turned out that we can't live without the `dist` files.

`postinstall` in package.json only worked when we install phenogrid directly. Because when we install it directly using `npm install`, all the devDepencies are installed at the same time. Then `postinstall` was able to use gulp/browserify to create the bundled files in `dist`.

BUT when we install phenogrid via monarch-app, all the devDepencies of phenogrid are not installed. Then there's no way we can use gulp/browserify to create the bundled files for phenogrid.

Form another perspective, the `dist` bundled files are just like `jquery.min.js`, it's part of the distribution. They should be in the package by default, unless the developers want to make changes to phenogrid source files and recreate the bundles.

**Comment by harryhoch** [comment]
Ok. it was worth a shot...

**Comment by yuanzhou** [comment]
It took me several hours to find this out. I tried several things to run gulp bundle via monarch-app, and all failed. At least now I can start the npm publish.
