### ISSUE TITLE
Grid cell tootip content formatting

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/phenogrid#190]
It can be somewhat confusing to use underline for 'In common", "Match", "Target" but not for "Source". Just need to format the content to make it more readable and less guesswork.

![capture](https://cloud.githubusercontent.com/assets/195873/10002836/648dd038-6077-11e5-81ab-4efb948465b1.PNG)

**Comment by yuanzhou** [comment]
Should we also use the name of "Phenotype" and "Gene" instead of "Source" and "Target" in the cell tooltip by making the source name configurable? Similar to what we did to "Unmatched Phenotypes"? @harryhoch @davism84 

And what are the differences between "Match" and "In-common"?

**Comment by harryhoch** [comment]
On Sep 21, 2015, at 3:56 PM, yuanzhou <notifications@github.com<mailto:notifications@github.com>> wrote:


Should we also use the name of "Phenotype" and "Gene" instead of "Source" and "Target" in the cell tooltip by making the source name configurable? Similar to what we did to "Unmatched Phenotypes"? @harryhoch<https://github.com/harryhoch> @davism84<https://github.com/davism84>

yes, please

And what are the differences between "Match" and "In-common"?

“Match” is the target phenotype that is most similar. “In-Common” is the subsuming phenotype -ie, the one that is the least common ancestor (in the phenotype hierarchy) of the source and the match.



—
Reply to this email directly or view it on GitHub<https://github.com/monarch-initiative/phenogrid/issues/190#issuecomment-142092379>.

----
Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics
harryh@pitt.edu<mailto:harryh@pitt.edu>  412 648 9300

**Comment by davism84** [comment]
labels will now use the type: attribute specified with the data

![image](https://cloud.githubusercontent.com/assets/10049022/10049124/260a599e-61e4-11e5-9288-331e748fcfdc.png)
