### ISSUE TITLE
gridSkeletonDataVendor still required?

### ISSUE THREAD

**Issue by julesjacobsen** [monarch-initiative/phenogrid#242]
gridSkeletonDataVendor == "IMPC" in all cases, so what's the requirement of having gridSkeletonDataVendor to go with gridSkeletonData? If there is gridSkeletonData, can you not just load it?

**Comment by yuanzhou** [comment]
Yes Sir! It's still required for now. For two reasons: 

1. Monarch use case has a different tooltip rendering

2. Monarch doesn't provide all the source phenotype labels/terms as IMPC does, so I'll have to send out extra calls to grab those labels for UNMATCHED phenotypes.

**Comment by julesjacobsen** [comment]
Ah, OK. So this is a Monarch 'issue' where they don't fully implement the phenogrid skeleton data. Can I suggest that the gridSkeletonDataVendor be removed for IMPC and changed to MONARCH. Assuming that the current IMPC setup is the more generic use-case. Do ZFin use the gridSkeletonDataVendor == IMPC for example? That would be weird. If everyone is a special case then forget it.

**Comment by yuanzhou** [comment]
Keeping the `gridSkeletonDataVendor: "IMPC"` is only one line of code in config, and change it to `Monarch` will require many other changes in Phenogrid, because there are several other use cases that are tied to Monarch's analyze/phenotypes section, which requires different data loading and rendering. Even if the current IMPC setup is more generic, Monarch is still the backend of Phenogrid, I'd rather make things easier to implement due to development history.
