### ISSUE TITLE
Can't read unmatched phenotypes

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/phenogrid#248]
The unmatched phenotypes come up in a box, but cannot be expanded to read long labels. I think expando/contracto at the bottom of the matched ones listed would be better.

See also #130 #245 and #247 

<img width="912" alt="cantread" src="https://cloud.githubusercontent.com/assets/796636/15808251/f22a0580-2b27-11e6-93e7-05422cd9889f.png">

**Comment by harryhoch** [comment]
@yuanzhou , would it be possible to revise the layout to account for the lengths of the labels?

**Comment by yuanzhou** [comment]
In the current version, the width of the unmatched box is calculated based on the actual width of the whole grid area. And a fixed length of the label is specified in CSS in order to align all the labels vertically. Showing the full length of each label will probably mess up the vertical alignment unless we show fewer columns with more space of each column. But this won't guarantee when there's a really long label and will create more gaps and longer list vertically.

Would it be a quick fix if I add `title` attribute to each linked label so we'll see the full label name on mouse hover?

**Comment by harryhoch** [comment]
would it not work to do fewer columns if labels are longer?

**Comment by yuanzhou** [comment]
Fixed and showing full label now. As a side effect, the labels won't be aligned vertically, which I think is fine.

![capture](https://cloud.githubusercontent.com/assets/195873/15825675/bad7000a-2bd2-11e6-908e-36f57bcb4291.PNG)
