### ISSUE TITLE
unmatched phenotypes problems

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#46]
Unmatched phenotypes are sometimes causing problems, in two ways:

1. Labels are coming up as "undefined", instead of having the text for the phenotype. 
2. Links are created relative to the originating site, not relative to the site where the phenogrid is being pulled from. 

See this pic from the UDPICS installation:

![phenogrid-udpics-unmatched](https://cloud.githubusercontent.com/assets/174707/6045462/4249cef0-ac68-11e4-97d6-f4077c26d92e.png)

Note how the unmatched  say "unmatched". They should instead display the phenotype label. 

Also, the links come out as 

http://udplims.nhgri.nih.gov/phenotype/HP_0003738 (or whatever). 

The hostname should refer to the host providing the data (tartini.crbs.ucsd.edu, monarchinitiative.org, etc.). 

You won't be able to get on to UDPICS, but please try to replicate and fix these links.

**Comment by VincentIII** [comment]
I believe that running phenogrid via /analyze does something similar.  It has to do with how the data pushed to /analyze is different from how reading info from a /disease page, so its unable to correctly read matches or in this case, non-matches.  I'll see if there is something I can do with altering how the unmatchedPhenotype functions handle data from somewhere other than the /disease pages

**Comment by VincentIII** [comment]
The issue is partially fixed for /analyze pages and UDP.  While it doesn't display the label (as its not part of the provided PhenotypeData given to phenogrid), it will properly display the ID if the label is undefined.  There was a function that would do a call to grab the label from the servers, but it took around a minute per ID to get the labels, and would not be worthwhile to use as it slowed down phenogrid way too much.  I might be able to get it to pull the info down the line when integrate the hashtables deeper into loadData().

For analyze, the provided data was solely the ID and not in an object, so it could not do a proper compare between the ID of the matched objects and each entry in the raw provided data.  Now if the ID is not in an object, it provides a dummy object skeleton it places it in so the unmatch functions run smoothly
