### ISSUE TITLE
loading data improvements

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/phenogrid#60]
Extract data load and transform to two new Javascript objects to separate loading concerns, isolated dependencies on owslim data format, simplify direct input of data as done with exomiser integration, etc. 

perhaps include validator -https://github.com/monarch-initiative/phenogrid/issues/52

should address concerns related to https://github.com/monarch-initiative/phenogrid/issues/49

**Comment by VincentIII** [comment]
Right now in the loadData functions, _loadOverviewData calls _loadSpeciesData three times to compile it's own data.  _loadSpeciesData could be transformed into a constructor for speciesData, but then _loadOverviewData will have to be rebuilt to appropriately build it's own object based off the pre-created objects.  It would also be suggested that these objects be cached, similar to how the hpoCache is built and protected, in order to cut down on repeated api calls that end up just wasting resources.

**Comment by harryhoch** [comment]
mike davis fixing this in monarch-app phenoMiz-hh branch  - will be moved back  into this repo when done.
